# Generated by Django 4.1.1 on 2022-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadatro_Lojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RAZAO_SOCIAL', models.CharField(max_length=100)),
                ('CNPJ', models.CharField(max_length=20)),
                ('NOME_FANTASIA', models.CharField(max_length=100)),
                ('RESPONSAVEL', models.CharField(max_length=100)),
                ('VENDEDOR', models.CharField(max_length=100)),
                ('AUTOMACAO', models.CharField(max_length=50)),
                ('ANALISTA', models.CharField(max_length=50)),
                ('DATA_ATIVACAO', models.DateField()),
                ('STATUS', models.CharField(max_length=50)),
            ],
        ),
    ]
